version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./dbdata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080